config/routes.rb
Rails.application.routes.draw do
 root 'static_pages#home'

  match '/about', to: 'static_pages#about', via: 'get'
  match '/help', to: 'static_pages#help', via: 'get'
  match '/contact', to: 'static_pages#contact', via: 'get'
  
  resources :users

end

app/models/user.rb
class User < ActiveRecord::Base
 
  def self.search(query)
    where("dna like ?", "%#{query}%") 
end
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def help
  end

  def about
  end

  def contact
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    if params[:search]
    @users = User.search(params[:search]).order("created_at DESC")
  else
    @users = User.all.order('created_at DESC')
  end
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name, :email)
    end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>CodonCoder | <%= yield(:title) %></title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <header>
    <div class="navbar navbar-fixed-top navbar-default">
        <div class="container-fluid">
            <div class="navbar-header">
              <%= link_to "CodonCoder", '/', id: "logo" %>
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
            </div>
            
            <div class="collapse navbar-collapse">
                <ul class="nav navbar-nav pull-right">
                   <li><%= link_to "Home", '/' %></li>
                   <li><%= link_to "Sequence", '/sequence' %></li>
                   <li><%= link_to "Help", '/help' %></li>  
                 </ul>
            </div>
        </div>
    </div>

</header>
  <div class="container">
   <%= yield %>
  <footer class="footer">
  <nav>
    <ul>
      <li><%= link_to "About", '/about' %></li>
      <li><%= link_to "Contact", '/contact' %></li>
    </ul>
  </nav>
  </footer>
  </div>


 <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
    <!-- Include all compiled plugins (below), or include individual files as needed -->
    <script src="js/bootstrap.min.js"></script>
    <script>$(".content-container-1,.content-container-2 ").css("min-height", $(window).height());</script>
</body>
</html>

app/views/static_pages/about.html.erb
<% provide(:title, 'About') %>
<h1>About</h1>
<style>
   
  text-center div{
    width:800px; text-align: center;
  }
  text-center p{
    
    text-align:center; 
  }
  
</style>
<body>
  <div class = "center">
    
<p>In this website you can have an amino acid sequence display codon seqence possibilites.</p>
<p>For any questions please visit the help page in the top right corner</p>
<p>This website was designed by a student at DePauw Univeristy as a senior project. It was
  coded and developed by a Computer Science and Biology double major who was inspired to combine
  both of his fields</p>
   </div>

app/views/static_pages/contact.html.erb
<% provide(:title, 'Contact') %>
<h1>Contact Info</h1>

<style>
  
p.ex {
    height: 100px;
    width: 1000px;
   text-align: center;
 }  
  
p{ 
      display: table;
      margin:auto;
     
}
</style>

<body>
  
  <p class="ex">If there are any problems or issuses to report with the page, formatting, errors or questions
    the help page could not answer please email alexanderspears_2015@depauw.edu </p>
 
 </body>

app/views/static_pages/help.html.erb
<% provide(:title, 'Help') %>
<h1>Help</h1>

<style>
p.ex {
    height: 100px;
    width: 1000px;
   text-align: center;
 }  
  
p{ 
      display: table;
      margin:auto;
}
</style>

<body>
   <div class = "center">
    <b><i>What is CodonCoder?</i></b>
    <br>
        It is a website where amino acids are uploaded and a graphic display of your matching codon possibilites will be displayed.<br>
    <br>
      <b><i>How does CodonCoder work?</i></b>
    <br>
      CodonCoder uses database matching to pattern match your inputted sequences to a database of matched codons ensuring consistent outputted                 results.
    <br>
     <br>
     <b>The following video conceptualizes codon sequencing by hand</b>
     <br>
      <br>  
         If you need additional help visit the contact page.
      <br>
    <br>
  
  </p>  
  </div>
</body>

<body>
  <div class="center">
    <iframe width="560" height="315" src="https://www.youtube.com/embed/Z4wZxraE59o" frameborder="0" allowfullscreen></iframe>
  </div>

</body> 

app/views/static_pages/home.html.erb
<% provide(:title, 'Home') %>
<div class="center hero-unit">
<h1>Welcome to the CodonCoder Application</h1>
  <%= link_to "Translate mRNA Now!", new_user_path,
class: "btn btn-large btn-primary" %>
  
  <p> </p>
</div>

<html lang="en">
  
<head>
  <style>
  <title>Bootstrap Example</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
  <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js"></script>
    
     div.padded {  
      padding-top: 10px;  
      padding-right: 0px;  
      padding-bottom: 0.25in;  
      padding-left: 5em;  
    }  
    
    </style>
</head>
   
  
  <body>
    <div class = "center">
    <strong>Click on the button and input a sequence to begin converting your amino acids to codons.</strong>
      </div>
    <div class="padded">  
   <br>  
   <br>
   <br>  
   <br> 
   <br>  
   <br>    
      
      </div>
    </body>
  
 
<body>
  
<p class = "padding">
  
<div class="container-fluid">
   
  <div class = "pull-left">
    
    <h3>Additional sequencing resources</h3>
  <p>The following pages can be used to BLAST protein sequences or display nucleotide sequences in a uesful graphic .</p>
    
    </div>
  </div>
  <div class="container">
  <div class="well well-lg" style="margin:10px">
  <div class="row">
  <div class="row">
    <div class="col-md-5 pull-left" style="background-color:lightgrey;">
      <div class="hidden-lg hidden-md hidden-sm">&nbsp;</div>
        <p>Please click on the image to do Nucleotide BLAST search using NCBI website.</p>
            <div class = "center">
            <%= link_to image_tag("NCBI.jpg", alt: "Rails logo", height:"142", width:"300"),'http://blast.ncbi.nlm.nih.gov/Blast.cgi?        
                PROGRAM=blastn&PAGE_TYPE=BlastSearch&LINK_LOC=blasthome' %>
              </div>
         <br>
      <p></p>
        </div>
      <div class="col-md-5 pull-right" style="background-color:lightgrey;">
        <p>Please click on the image to do sequence nucleotides and display in a graphic.</p>
        <div class = "center">
          <%= link_to image_tag("atlas_plasmid.jpg", alt: "Rails logo", height:"142", width:"300"),'https://www.dna20.com/eCommerce/tools/atlas-
            plasmid-mapper' %>  
          </div>
         <br>
      <p></p>
    </div>
  </div>
</div>
      </div>
     </div>
  </p>
    
</body>
</html>

app/views/users/_form.html.erb
<body>
    <div class="content-container-1" id="div3">
       <div class="container">
          <div class="row text-center">
            <h3>Add your sequence here</h3>

          </div>

           <div class="row text-center pt mb">
             <div class="col-md-6 col-md-offset-3">
                <br>

              <%= form_tag(users_path, :method => "get", id: "search-form") do %>
              <%= text_area_tag :search, params[:search], placeholder: "Translate DNA codons...", 
              :size =>"75x10", class: "form-control"%> 
               <br>
              <%= submit_tag "Search", :name => nil, :mrna => nil %>
              <% end %> 

            </div>
        </div>
    </div>
</div>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'form' %>


<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<h1>Sequence Results</h1>

<table>
  <thead>
    <tr>
      <th>full</th>
      <th>dna</th>
      <th>mrna</th>
      <th colspan="4"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.full %></td>
        <td><%= user.dna %></td>
        <td><%= user.mrna %></td>
       </tr>
    <% end %>
  </tbody>
</table>

app/views/users/new.html.erb
<h1>New Sequence</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>full:</strong>
  <%= @user.full %>
</p>

<p>
  <strong>dna:</strong>
  <%= @user.dna %>
  
  <strong>mrna:</strong>
  <%= @user.mrna %>
</p>

<%= link_to 'Back', users_path %>